---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-google-sheets/google_sheets_source/models/definitions/spreadsheet_values.yaml
title: SpreadsheetValues
description: "Partial declaration of the GoogleSheets API Schema. We use a small portion of the full API specified here: https://developers.google.com/sheets/api/reference/rest/v4"
type: object
additionalProperties: true
required:
  - valueRanges
  - spreadsheetId
properties:
  spreadsheetId:
    type: string
  valueRanges:
    type: array
    items:
      "$ref": "#/definitions/ValueRange"
definitions:
  ValueRange:
    additionalProperties: true
    type: object
    properties:
      values:
        type: array
        items:
          "$ref": "#/definitions/Values"
  Values:
    type: array
    items:
      type: string

